version: "3.3"

services:
  postgres-to-csv:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres-to-csv
    working_dir: /app
    volumes:
      - ./output:/output
    environment:
      POSTGRES_HOST: "172.16.182.32"
      POSTGRES_PORT: "5432"
      POSTGRES_USER: "your_username"
      POSTGRES_PASSWORD: "your_password"
      POSTGRES_DB: "test_uris_main"
